// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearTaskChannel():Promise<boolean>;

export function DirectoryPicker():Promise<main.DirectoryPickerResponse>;

export function FilePicker():Promise<main.FilesPickerResponse>;

export function GetUserDownloadsDir():Promise<main.DirectoryPickerResponse>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function IsWin11():Promise<boolean>;

export function NewWorker(arg1:main.ProcessWorker):Promise<boolean>;

export function ParseFileName(arg1:string):Promise<string>;

export function RemoveWorker(arg1:string):Promise<boolean>;

export function SetRimageParams(arg1:main.RimageParams):Promise<boolean>;

export function SetTaskChannel(arg1:Array<main.Task>):Promise<boolean>;
