// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DirectoryPicker():Promise<main.DirectoryPickerResponse>;

export function FileNameParser(arg1:string):Promise<string>;

export function FilePicker():Promise<main.FilesPickerResponse>;

export function Greet(arg1:string):Promise<string>;

export function IsDirectory(arg1:string):Promise<boolean>;
