// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTaskChannel() {
  return window['go']['main']['App']['ClearTaskChannel']();
}

export function DirectoryPicker() {
  return window['go']['main']['App']['DirectoryPicker']();
}

export function FilePicker() {
  return window['go']['main']['App']['FilePicker']();
}

export function GetUserDownloadsDir() {
  return window['go']['main']['App']['GetUserDownloadsDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsDirectory(arg1) {
  return window['go']['main']['App']['IsDirectory'](arg1);
}

export function NewWorker(arg1) {
  return window['go']['main']['App']['NewWorker'](arg1);
}

export function ParseFileName(arg1) {
  return window['go']['main']['App']['ParseFileName'](arg1);
}

export function RemoveWorker(arg1) {
  return window['go']['main']['App']['RemoveWorker'](arg1);
}

export function SetTaskChannel(arg1) {
  return window['go']['main']['App']['SetTaskChannel'](arg1);
}
