// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirectoryPicker() {
  return window['go']['main']['App']['DirectoryPicker']();
}

export function FileNameParser(arg1) {
  return window['go']['main']['App']['FileNameParser'](arg1);
}

export function FilePicker() {
  return window['go']['main']['App']['FilePicker']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsDirectory(arg1) {
  return window['go']['main']['App']['IsDirectory'](arg1);
}
